name: sampleproject1

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Upgrade pip
        run: python -m pip install --upgrade pip
      - name: Start local web server
        run: nohup python -m http.server 8000 --directory pythonproject1 &
      - name: Wait for the web server to start
        run: sleep 5 
      - name: Print Hello World
        run: |
          print("Hello World!")
          print("Welcome to sample python project creation")
