name: sampleproject1

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Upgrade pip
        run: python -m pip install --upgrade pip
      - name: Start local web server
        run: python -m http.server 8000 --directory ./
         print("Hello World!")
