name: sampleproject1

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Upgrade pip
        run: python -m pip install --upgrade pip
      - name: run index.htmlfile
        run: index.html
        

        
